packages:
  - apps/*
  - packages/*

catalog:
  '@chromatic-com/storybook': ^4.1.1
  '@storybook/addon-a11y': ^10.0.0
  '@storybook/addon-docs': ^10.0.0
  '@storybook/addon-onboarding': ^10.0.0
  '@storybook/react-vite': ^10.0.0
  '@stzhu/eslint-config': ^0.9.0
  '@stzhu/prettier-plugin-tsconfig': ^0.7.0
  '@stzhu/tsconfig': ^0.1.0
  '@types/node': ^24.9.2
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  electron: ^39.0.0
  eslint: ^9.38.0
  hono: ^4.10.3
  react: ^19.2.0
  react-dom: ^19.2.0
  storybook: ^10.0.0
  tailwindcss: 4.1.16
  typescript: ^5.9.3
  vite: ^7.1.12

catalogs:
  expo:
    '@types/react': ~19.1.0
    '@types/react-dom': ~19.1.0
    expo: ~54.0.21
    react: 19.1.0
    react-dom: 19.1.0
    react-native: 0.81.5

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - electron
  - electron-winstaller
  - esbuild
  - sharp
  - spawn-sync
  - unrs-resolver
  - workerd

overrides:
  lightningcss: 1.30.1

patchedDependencies:
  '@electron-toolkit/typed-ipc': patches/@electron-toolkit__typed-ipc.patch
  electron-vite: patches/electron-vite.patch

saveWorkspaceProtocol: rolling

strictDepBuilds: true
