packages:
  - apps/*
  - packages/*

catalog:
  '@chromatic-com/storybook': ^4.1.3
  '@storybook/addon-a11y': ^10.1.10
  '@storybook/addon-docs': ^10.1.10
  '@storybook/addon-onboarding': ^10.1.10
  '@storybook/addon-vitest': ^10.1.10
  '@storybook/react-vite': ^10.1.10
  '@stzhu/eslint-config': ^0.9.0
  '@stzhu/prettier-plugin-tsconfig': ^0.7.0
  '@stzhu/tsconfig': ^0.1.0
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  electron: ^39.2.7
  eslint: ^9.39.2
  hono: ^4.11.1
  react: ^19.2.3
  react-dom: ^19.2.3
  storybook: ^10.1.10
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  vite: ^7.3.0
  vitest: ^4.0.16

catalogs:
  expo:
    '@types/react': ~19.1.17
    '@types/react-dom': ~19.1.11
    expo: ~54.0.30
    react: 19.1.0
    react-dom: 19.1.0
    react-native: 0.81.5

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - electron
  - electron-winstaller
  - esbuild
  - msw
  - sharp
  - spawn-sync
  - unrs-resolver
  - workerd

overrides:
  lightningcss: 1.30.1

patchedDependencies:
  '@electron-toolkit/typed-ipc': patches/@electron-toolkit__typed-ipc.patch
  electron-vite: patches/electron-vite.patch

saveWorkspaceProtocol: rolling

strictDepBuilds: true
